package com.eukolos.cryptoexchange.enumaration;


public enum EnumCurrency {
    USD("United States Dollar"),
    ADA("Cardano"),
    ALGO("Algorand"),
    AMP("Amp"),
    ANKR("Ankr"),
    ANT("Aragon"),
    AR("Arweave"),
    ARDR("Ardor"),
    ATOM("Cosmos"),
    AUDIO("Audius"),
    AVA("Travala.com"),
    AVAX("Avalanche"),
    AXS("Axie Infinity"),
    BAL("Balancer"),
    BAND("Band Protocol"),
    BAT("Basic Attention Token"),
    BCH("Bitcoin Cash"),
    BNB("Binance Coin"),
    BOA("Bosagora"),
    BOND("BarnBridge"),
    BTC("Bitcoin"),
    BTG("Bitcoin Gold"),
    BTT("BitTorrent"),
    BUSD("Binance USD"),
    CAKE("PancakeSwap"),
    CEL("Celsius"),
    CHZ("Chiliz"),
    CKB("Nervos Network"),
    COMP("Compound"),
    CRO("Crypto.com Coin"),
    CRV("Curve DAO Token"),
    CVC("Civic"),
    DAI("Dai"),
    DASH("Dash"),
    DENT("Dent"),
    DGB("DigiByte"),
    DIA("DIA"),
    DNT("district0x"),
    DOGE("Dogecoin"),
    DOT("Polkadot"),
    EGLD("Elrond"),
    ENJ("Enjin Coin"),
    EOS("EOS"),
    ETC("Ethereum Classic"),
    ETH("Ethereum"),
    FET("Fetch.ai"),
    FIL("Filecoin"),
    FLOW("Flow"),
    FTM("Fantom"),
    GNT("Golem"),
    GRT("The Graph"),
    GVT("Genesis Vision"),
    HBAR("Hedera Hashgraph"),
    HIVE("Hive"),
    HNT("Helium"),
    HOT("Holo"),
    HT("Huobi Token"),
    ICP("Internet Computer"),
    ICX("ICON"),
    INJ("Injective Protocol"),
    IOST("IOST"),
    KAVA("Kava"),
    KMD("Komodo"),
    KNC("Kyber Network"),
    KSM("Kusama"),
    LEO("UNUS SED LEO"),
    LINK("Chainlink"),
    LRC("Loopring"),
    LSK("Lisk"),
    LTC("Litecoin"),
    LUNA("Terra"),
    MANA("Decentraland"),
    MATIC("Polygon"),
    MCO("Crypto.com"),
    MDX("Mdex"),
    MIOTA("IOTA"),
    MKR("Maker"),
    MLN("Melon"),
    MTL("Metal"),
    NANO("Nano"),
    NEAR("NEAR Protocol"),
    NEO("NEO"),
    NEXO("Nexo"),
    NKN("NKN"),
    NMR("Numeraire"),
    NRV("Nerve Finance"),
    NSBT("Neutrino System Base Token"),
    NULS("NULS"),
    OCEAN("Ocean Protocol"),
    OMG("OMG Network"),
    OMI("ECOMI"),
    ONE("Harmony"),
    ONT("Ontology"),
    ORN("Orion Protocol"),
    OXT("Orchid"),
    PAX("Paxos Standard"),
    PERP("Perpetual Protocol"),
    PNT("pNetwork"),
    POWR("Power Ledger"),
    QNT("Quant"),
    QTUM("Qtum"),
    RARI("Rarible"),
    REN("Ren"),
    REP("Augur"),
    RSR("Reserve Rights"),
    RUNE("THORChain"),
    RVN("Ravencoin"),
    SAND("The Sandbox"),
    SBD("Steem Dollars"),
    SC("Siacoin"),
    SLP("Small Love Potion"),
    SNX("Synthetix"),
    SOL("Solana"),
    SRM("Serum"),
    STORJ("Storj"),
    STX("Stacks"),
    SUSHI("SushiSwap"),
    SWRV("Swerve"),
    SXP("Swipe"),
    SYS("Syscoin"),
    TEL("Telcoin"),
    TFUEL("Theta Fuel"),
    THETA("Theta Network"),
    TOMO("TomoChain"),
    TRAC("OriginTrail"),
    TRB("Tellor"),
    TRU("TrueFi"),
    TRX("TRON"),
    TUSD("TrueUSD"),
    UMA("UMA"),
    UNI("Uniswap"),
    USDC("USD Coin"),
    USDK("USDK"),
    USDT("Tether"),
    UTK("UTRUST"),
    VET("VeChain"),
    VGX("Voyager Token"),
    VTHO("VeThor Token"),
    WAXP("WAX Protocol Token"),
    WBTC("Wrapped Bitcoin"),
    WICC("WaykiChain"),
    WIN("WINkLink"),
    WOZX("EFFORCE"),
    WRX("WazirX"),
    XEM("NEM"),
    XLM("Stellar"),
    XMR("Monero"),
    XNK("Ink Protocol"),
    XRP("XRP"),
    XTZ("Tezos"),
    XVG("Verge"),
    YFI("yearn.finance"),
    YFII("DFI.Money"),
    YOYOW("YOYOW"),
    ZEC("Zcash"),
    ZEN("Horizen"),
    ZIL("Zilliqa"),
    ZRX("0x");

    private final String description;

    EnumCurrency(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
